- script/seed.js
- server/db/models/election.js
> wrote first draft seed file, missing foreign keys

- package-lock.json
- package.json
- script/seed.js
> all fields now included in seed file

- client/components/user-home.js
- client/store/index.js
- client/store/user-home.js
- server/api/elections.js
- server/db/models/election.js
> User home2

- ADDRESS
- client/components/user-home.js
- client/store/index.js
- client/store/user-home.js
- ethereum/deploy.js
- ethereum/factory.js
- ethereum/web3.js
- package-lock.json
- package.json
- server/api/elections.js
- server/db/models/election.js
- test/Election.test.js
> factory contract deployed!

- client/components/index.js
- client/components/watch-party.js
- client/routes.js
- package-lock.json
- package.json
> watch party ready to be added to master

- client/components/user-home.js
> Setting up ethereum

- client/components/admin-home.js
- client/components/user-home.js
- client/components/watch-party.js
- client/store/index.js
- client/store/watch-party.js
> admin can create an election!!!!!!!!

- client/components/create-election.js
- client/components/index.js
- client/components/navbar.js
- client/routes.js
> Change name

- ADDRESS
- client/components/create-election.js
- client/store/user-home.js
- ethereum/contracts/Election.sol
- ethereum/factory.js
> doin' stuff

- ADDRESS
- client/components/user-home.js
> creating place to save election addresses

- client/components/voting-booth.js
- client/components/watch-party.js
- client/store/watch-party.js
> Reworked voting booth and watch party components so they use our new routes and thunks

- client/components/voting-booth.js
> Blockchain vb

- client/components/voting-booth.js
- client/socket.js
- client/store/watch-party.js
- server/socket/index.js
> setting up sockets

- client/components/bar-chart.js
- client/components/donut-chart.js
- client/components/watch-party.js
- client/store/candidate.js
- script/altSeed.js
- script/oldSeed.js
- script/seed.js
> Made charts dynamic and up to date with store, added altSeed file for viewing chart.

- client/components/create-candidate.js
- client/components/create-election.js
- client/components/history.js
- client/components/index.js
- client/components/past-donut-chart.js
- client/components/voting-booth.js
- client/routes.js
> added spinner

- client/components/create-candidate.js
- client/components/create-election.js
- client/components/login-form.js
- client/components/signup-form.js
- client/components/voting-booth.js
- public/style.css
> Page styling2

- client/components/create-candidate.js
- client/components/create-election.js
- client/components/history.js
- client/components/voting-booth.js
- server/api/communities.js
- server/db/models/candidate.js
- server/db/models/election.js
> Description fields

- client/components/create-candidate.js
- client/components/create-election.js
> Formatting form

- ADDRESS
- ethereum/factory.js
> added factory address

- client/components/create-candidate.js
- client/components/create-election.js
- client/components/voting-booth.js
> added linear spinner to createCandidate and createElection

- client/components/app-bar.js
- client/components/user-home.js
- client/components/voting-booth.js
- public/style.css
> incorporating changes from code review

- client/components/app-bar.js
- public/style.css
> sticky navbar is implemented

- package-lock.json
- package.json
- server/api/index.js
- server/api/mail.js
- server/index.js
> added mailing functionality

- client/components/all-community-members.js
- client/store/community.js
- server/api/mail.js
> admin can send emails in community members

- client/components/create-candidate.js
- client/components/create-election.js
- client/components/voting-booth.js
> Vote checkbox

- client/components/all-community-members.js
- public/style.css
> styling branch

- client/components/app-bar.js
- client/components/bar-chart.js
- client/components/donut-chart.js
- client/components/logged.js
> changed graph position and FAQ link

- client/components/app-bar.js
- client/components/logged.js
> Stepper- added tutorial link to upper right hand nav bar

- client/components/user-home.js
- client/components/voting-booth.js
- public/style.css
> Last minute styles

- client/components/voting-booth.js
> voting fixed

- ADDRESS
- script/seed.js
> seed file working

- client/components/user-home.js
- client/components/voting-booth.js
- public/style.css
> 0517 styling

- client/components/about-page.js
- client/components/user-home.js
- script/seed.js
> fixed election address

- client/components/user-home.js
- public/style.css
> upcoming election box styling

- client/components/user-home.js
- public/style.css
> added candidates for upcoming election

- client/components/create-candidate.js
- public/style.css
> fixed candidate toast
